name: gosh-fetch
version: '2.0.0'
title: Gosh Fetch
summary: Modern download manager for Linux
description: |
  Gosh Fetch is a powerful and modern download manager for Linux with support
  for HTTP, HTTPS, and BitTorrent downloads. Built with GTK4 and libadwaita for
  a native GNOME experience.

  Features:
  - HTTP/HTTPS downloads with resume support
  - BitTorrent and magnet link support
  - Download scheduling and queue management
  - System tray integration
  - Modern, adaptive UI
license: AGPL-3.0
contact: https://github.com/goshitsarch-eng/Gosh-Fetch-Linux/issues
source-code: https://github.com/goshitsarch-eng/Gosh-Fetch-Linux
issues: https://github.com/goshitsarch-eng/Gosh-Fetch-Linux/issues
website: https://github.com/goshitsarch-eng/Gosh-Fetch-Linux

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
  amd64:
  arm64:

layout:
  /usr/share/libadwaita-1:
    bind: $SNAP/usr/share/libadwaita-1

apps:
  gosh-fetch:
    command: bin/gosh-fetch-gtk
    desktop: usr/share/applications/io.github.gosh.Fetch.desktop
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - removable-media
    slots:
      - dbus-daemon
    common-id: io.github.gosh.Fetch

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: io.github.gosh.Fetch

parts:
  gosh-fetch:
    plugin: rust
    source: .
    build-packages:
      - libgtk-4-dev
      - libadwaita-1-dev
      - libdbus-1-dev
      - libssl-dev
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libdbus-1-3
    rust-channel: stable
    rust-path:
      - crates/gosh-fetch-gtk
    override-build: |
      craftctl default
      install -Dm644 ${CRAFT_PART_SRC}/gosh-fetch.desktop ${CRAFT_PART_INSTALL}/usr/share/applications/io.github.gosh.Fetch.desktop
      install -Dm644 ${CRAFT_PART_SRC}/io.github.gosh.Fetch.metainfo.xml ${CRAFT_PART_INSTALL}/usr/share/metainfo/io.github.gosh.Fetch.metainfo.xml
      install -Dm644 ${CRAFT_PART_SRC}/resources/io.github.gosh.Fetch.png ${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/256x256/apps/io.github.gosh.Fetch.png
